name: Get & Cache dependencies (custom action)
description: Get the dependencies and cache them
inputs:
  input-1:
    description: the input 1 name
    required: true
  caching:
    description: if cache is needed
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: input.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
    - name: Output input 1
      run: echo ${{ inputs.input-1 }}
      shell: bash