name: Reusable Deploy
on:
  workflow_call:
      inputs:
        artifact-name:
          description: The artifact name
          required: false
          default: dist
          type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Show secrets
        run: echo "secret= ${{ secrets.MY_PASSWORD }}"
      - name: Output Information
        run: echo "deploying and uploading..."