name: Reusable Deploy
on:
  workflow_call:
      inputs:
        artifact-name:
          description: The artifact name
          required: false
          default: dist
          type: string
      outputs:
        result:
          description: The result description
          value: ${{ jobs.deploy.outputs.outcome }}
      # secrets:
        # some-secret:
          # required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Show secrets
        run: echo "secret= ${{ secrets.MY_PASSWORD }}" # add secrets: inherit to the caller if propagate secrets or add secrets in workflow_call.secrets
      - name: Output Information
        run: echo "deploying and uploading..."
      - name: Result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT